import type { Applicant } from "@/domain/hiring/pipeline";

/**
 * Deterministic demo seed for the Hiring pipeline.
 *
 * APPLICANTS ARE FICTIONAL. Unlike staff, an applicant has not been hired —
 * naming a real person as having applied to, been rejected by, or failed a
 * background check at a home care agency is a disclosure about them that they
 * never agreed to. Recruiters are Joy's real team, which is fine.
 *
 * States chosen to exercise the rules rather than to look tidy: one blocked at
 * offer because the background check has not cleared, one stale in Applied, one
 * in onboarding who cannot take a first shift because documents are missing,
 * one ready to become an active employee, and three closed with their reasons.
 */
export const seedApplicants: Applicant[] = [
  {
    id: "app-ortega",
    name: "Marisol Ortega",
    roleApplied: "Caregiver — CNA",
    track: "hiring",
    stage: "interview",
    stageSince: "2026-08-16",
    appliedOn: "2026-08-03",
    source: "Indeed",
    recruiter: "John Segura",
    email: "m.ortega@example.com",
    phone: "(713) 555-0142",
    availability: "Weekdays, mornings",
    drives: true,
    documents: {
      handbook: { issued: "2026-07-25", expires: "2027-07-25" },
    },
  },
  {
    id: "app-hill",
    name: "Terrance Hill",
    roleApplied: "Caregiver — CNA",
    track: "hiring",
    stage: "documents",
    stageSince: "2026-08-14",
    appliedOn: "2026-07-30",
    source: "Referral",
    recruiter: "John Segura",
    email: "t.hill@example.com",
    phone: "(281) 555-0117",
    availability: "Weekdays, open",
    drives: true,
    documents: {
      handbook: { issued: "2026-07-25", expires: "2027-07-25" },
      licence: { issued: "2024-01-15", expires: "2028-01-15" },
      cpr: { issued: "2025-06-01", expires: "2027-06-01" },
    },
  },
  {
    id: "app-bello",
    name: "Aisha Bello",
    roleApplied: "LVN case manager",
    track: "hiring",
    stage: "background",
    stageSince: "2026-08-15",
    appliedOn: "2026-07-28",
    source: "Indeed",
    recruiter: "Kelsey Westley",
    email: "a.bello@example.com",
    phone: "(832) 555-0198",
    availability: "Mon–Fri, days",
    drives: true,
    // No background_check yet, so the offer is blocked. This is the record that
    // demonstrates the one hiring rule that is a liability rather than tidiness.
    documents: {
      handbook: { issued: "2026-07-25", expires: "2027-07-25" },
      licence: { issued: "2024-01-15", expires: "2028-01-15" },
      cpr: { issued: "2025-06-01", expires: "2027-06-01" },
      tb_test: { issued: "2026-07-22", expires: "2027-07-22" },
    },
  },
  {
    id: "app-nguyen",
    name: "Kevin Nguyen",
    roleApplied: "Scheduling coordinator",
    track: "hiring",
    stage: "phone_screen",
    stageSince: "2026-08-17",
    appliedOn: "2026-08-04",
    source: "Website",
    recruiter: "John Segura",
    email: "k.nguyen@example.com",
    phone: "(713) 555-0176",
    availability: "Mon–Fri, days",
    drives: false,
    documents: {},
  },
  {
    id: "app-lopez",
    name: "Brianna Lopez",
    roleApplied: "Caregiver — HHA",
    track: "hiring",
    stage: "applied",
    // Sitting untouched for over a week. Good applicants take other jobs.
    stageSince: "2026-08-05",
    appliedOn: "2026-08-05",
    source: "Facebook",
    recruiter: null,
    email: "b.lopez@example.com",
    phone: "(346) 555-0133",
    availability: "Weekend nights",
    drives: false,
    documents: {},
  },
  {
    id: "app-medina",
    name: "Rosa Medina",
    roleApplied: "Caregiver — CNA",
    track: "onboarding",
    stage: "offer",
    onboardingStage: "field_orientation",
    stageSince: "2026-08-15",
    appliedOn: "2026-07-08",
    source: "Referral",
    recruiter: "John Segura",
    email: "r.medina@example.com",
    phone: "(713) 555-0121",
    availability: "Weekdays, mornings",
    drives: true,
    offerAcceptedOn: "2026-07-25",
    // Missing the TB test, so the first shift is blocked.
    documents: {
      background_check: { issued: "2026-07-20", expires: "2029-07-20" },
      handbook: { issued: "2026-07-25", expires: "2027-07-25" },
      licence: { issued: "2024-01-15", expires: "2028-01-15" },
      cpr: { issued: "2025-06-01", expires: "2027-06-01" },
      drivers_license: { issued: "2023-03-02", expires: "2027-03-02" },
      auto_insurance: { issued: "2026-01-01", expires: "2027-01-01" },
    },
  },
  {
    id: "app-carter",
    name: "Jamal Carter",
    roleApplied: "Caregiver — HHA",
    track: "onboarding",
    stage: "offer",
    onboardingStage: "week_2",
    stageSince: "2026-08-16",
    appliedOn: "2026-07-15",
    source: "Indeed",
    recruiter: "John Segura",
    email: "j.carter@example.com",
    phone: "(832) 555-0188",
    availability: "Weekends",
    drives: false,
    offerAcceptedOn: "2026-08-01",
    // Everything in. Ready to become an active employee.
    documents: {
      background_check: { issued: "2026-07-20", expires: "2029-07-20" },
      tb_test: { issued: "2026-07-22", expires: "2027-07-22" },
      licence: { issued: "2024-01-15", expires: "2028-01-15" },
      cpr: { issued: "2025-06-01", expires: "2027-06-01" },
      handbook: { issued: "2026-07-25", expires: "2027-07-25" },
      immunizations: { issued: "2026-07-22", expires: "2027-07-22" },
      annual_training: { issued: "2026-07-30", expires: "2027-07-30" },
    },
  },
  {
    id: "app-vega",
    name: "Chris Vega",
    roleApplied: "Caregiver — CNA",
    track: "no_fit",
    stage: "interview",
    stageSince: "2026-07-29",
    appliedOn: "2026-07-21",
    source: "Indeed",
    recruiter: "John Segura",
    email: "c.vega@example.com",
    phone: "(832) 555-0144",
    availability: "—",
    drives: false,
    noFitReason: "interview_no_show",
    documents: {},
  },
  {
    id: "app-frost",
    name: "Danielle Frost",
    roleApplied: "LVN case manager",
    track: "no_fit",
    stage: "background",
    stageSince: "2026-08-02",
    appliedOn: "2026-07-22",
    source: "Referral",
    recruiter: "Kelsey Westley",
    email: "d.frost@example.com",
    phone: "(281) 555-0154",
    availability: "Mon–Fri, days",
    drives: true,
    noFitReason: "background_not_clear",
    documents: {
      handbook: { issued: "2026-07-25", expires: "2027-07-25" },
      licence: { issued: "2024-01-15", expires: "2028-01-15" },
    },
  },
  {
    id: "app-webb",
    name: "Marcus Webb",
    roleApplied: "Caregiver — CNA",
    track: "no_fit",
    stage: "offer",
    stageSince: "2026-08-08",
    appliedOn: "2026-06-30",
    source: "Website",
    recruiter: "John Segura",
    email: "m.webb@example.com",
    phone: "(713) 555-0163",
    availability: "Weekdays, evenings",
    drives: true,
    noFitReason: "withdrew",
    documents: {
      background_check: { issued: "2026-07-20", expires: "2029-07-20" },
      handbook: { issued: "2026-07-25", expires: "2027-07-25" },
      licence: { issued: "2024-01-15", expires: "2028-01-15" },
    },
  },
];
