// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/query-clients.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^4.4.3";
import { mockDB } from "npm:@/lib/mockData";

// src/lib/mcp/auth.ts
function requireAuth(ctx) {
  if (ctx?.isAuthenticated?.()) return null;
  return {
    content: [
      {
        type: "text",
        text: "Not authenticated. Sign in to Home Care Hub to use this tool."
      }
    ],
    isError: true
  };
}

// src/lib/mcp/tools/query-clients.ts
var query_clients_default = defineTool({
  name: "query_clients",
  title: "Query clients",
  description: "Search home-care clients by name or status. Returns matching clients with care plan, weekly hours, and primary caregiver.",
  inputSchema: {
    search: z.string().optional().describe("Partial, case-insensitive name match"),
    status: z.enum(["active", "on-hold", "discharged"]).optional(),
    limit: z.number().int().min(1).max(50).default(20)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ search, status, limit }, ctx) => {
    const denied = requireAuth(ctx);
    if (denied) return denied;
    const rows = mockDB.clients.filter((c) => status ? c.status === status : true).filter((c) => search ? c.name.toLowerCase().includes(search.toLowerCase()) : true).slice(0, limit).map((c) => ({
      id: c.id,
      name: c.name,
      status: c.status,
      carePlan: c.carePlan,
      hoursPerWeek: c.hoursPerWeek,
      primaryCaregiver: mockDB.employees.find((e) => e.id === c.primaryCaregiverId)?.name ?? null
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { count: rows.length, clients: rows }
    };
  }
});

// src/lib/mcp/tools/query-employees.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^4.4.3";
import { mockDB as mockDB2 } from "npm:@/lib/mockData";
var query_employees_default = defineTool2({
  name: "query_employees",
  title: "Query caregivers",
  description: "Search caregivers and staff by name, role, or status. Includes hours this week and credential expiry dates.",
  inputSchema: {
    search: z2.string().optional(),
    role: z2.enum(["Caregiver", "RN", "LPN", "Coordinator"]).optional(),
    status: z2.enum(["active", "on-leave", "inactive"]).optional(),
    limit: z2.number().int().min(1).max(50).default(20)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ search, role, status, limit }, ctx) => {
    const denied = requireAuth(ctx);
    if (denied) return denied;
    const rows = mockDB2.employees.filter((e) => role ? e.role === role : true).filter((e) => status ? e.status === status : true).filter((e) => search ? e.name.toLowerCase().includes(search.toLowerCase()) : true).slice(0, limit).map((e) => ({
      id: e.id,
      name: e.name,
      role: e.role,
      status: e.status,
      hoursThisWeek: e.hoursThisWeek,
      credentials: e.credentials,
      assignedClients: e.assignedClientIds.length
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { count: rows.length, employees: rows }
    };
  }
});

// src/lib/mcp/tools/query-shifts.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^4.4.3";
import { mockDB as mockDB3 } from "npm:@/lib/mockData";
function windowFor(when) {
  const now = /* @__PURE__ */ new Date();
  const start = new Date(now);
  start.setHours(0, 0, 0, 0);
  const end = new Date(start);
  switch (when) {
    case "tomorrow":
      start.setDate(start.getDate() + 1);
      end.setDate(start.getDate() + 1);
      break;
    case "this-week":
      end.setDate(start.getDate() + 7);
      break;
    case "next-week":
      start.setDate(start.getDate() + 7);
      end.setDate(start.getDate() + 7);
      break;
    case "past-week":
      start.setDate(start.getDate() - 7);
      break;
    default:
      end.setDate(start.getDate() + 1);
  }
  return [start, end];
}
var query_shifts_default = defineTool3({
  name: "query_shifts",
  title: "Query shifts",
  description: "Look up scheduled shifts in a date window, optionally filtered by caregiver, client, or shift status.",
  inputSchema: {
    when: z3.enum(["today", "tomorrow", "this-week", "next-week", "past-week"]).default("today"),
    caregiverName: z3.string().optional(),
    clientName: z3.string().optional(),
    status: z3.enum(["scheduled", "clocked-in", "completed", "missed", "cancelled"]).optional(),
    limit: z3.number().int().min(1).max(100).default(50)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ when, caregiverName, clientName, status, limit }, ctx) => {
    const denied = requireAuth(ctx);
    if (denied) return denied;
    const [from, to] = windowFor(when);
    const rows = mockDB3.shifts.filter((s) => {
      const start = new Date(s.start);
      return start >= from && start < to;
    }).filter((s) => status ? s.status === status : true).map((s) => ({
      id: s.id,
      start: s.start,
      end: s.end,
      status: s.status,
      caregiver: mockDB3.employees.find((e) => e.id === s.caregiverId)?.name ?? "Unknown",
      client: mockDB3.clients.find((c) => c.id === s.clientId)?.name ?? "Unknown",
      notes: s.notes ?? null
    })).filter(
      (s) => caregiverName ? s.caregiver.toLowerCase().includes(caregiverName.toLowerCase()) : true
    ).filter(
      (s) => clientName ? s.client.toLowerCase().includes(clientName.toLowerCase()) : true
    ).sort((a, b) => a.start.localeCompare(b.start)).slice(0, limit);
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { count: rows.length, window: when, shifts: rows }
    };
  }
});

// src/lib/mcp/tools/query-invoices.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^4.4.3";
import { mockDB as mockDB4 } from "npm:@/lib/mockData";
var query_invoices_default = defineTool4({
  name: "query_invoices",
  title: "Query invoices",
  description: "List billing invoices, optionally filtered by status or client name, with totals for the matching set.",
  inputSchema: {
    status: z4.enum(["draft", "sent", "paid", "overdue"]).optional(),
    clientName: z4.string().optional(),
    limit: z4.number().int().min(1).max(100).default(25)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ status, clientName, limit }, ctx) => {
    const denied = requireAuth(ctx);
    if (denied) return denied;
    const rows = mockDB4.invoices.filter((i) => status ? i.status === status : true).map((i) => ({
      id: i.id,
      number: i.number,
      client: mockDB4.clients.find((c) => c.id === i.clientId)?.name ?? "Unknown",
      amount: i.amount,
      status: i.status,
      periodStart: i.periodStart,
      periodEnd: i.periodEnd,
      issuedAt: i.issuedAt
    })).filter(
      (i) => clientName ? i.client.toLowerCase().includes(clientName.toLowerCase()) : true
    ).slice(0, limit);
    const total = rows.reduce((sum, r) => sum + r.amount, 0);
    return {
      content: [
        { type: "text", text: JSON.stringify({ total, invoices: rows }, null, 2) }
      ],
      structuredContent: { count: rows.length, total, invoices: rows }
    };
  }
});

// src/lib/mcp/tools/get-sop.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^4.4.3";
import { mockDB as mockDB5 } from "npm:@/lib/mockData";
var get_sop_default = defineTool5({
  name: "get_sops",
  title: "Get SOPs",
  description: "List standard operating procedures, or fetch the latest content of one SOP by id or title match.",
  inputSchema: {
    search: z5.string().optional().describe("Title or id to fetch full content for"),
    category: z5.string().optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ search, category }, ctx) => {
    const denied = requireAuth(ctx);
    if (denied) return denied;
    const filtered = mockDB5.sops.filter(
      (s) => category ? s.category.toLowerCase() === category.toLowerCase() : true
    );
    if (search) {
      const q = search.toLowerCase();
      const sop = filtered.find(
        (s) => s.id.toLowerCase() === q || s.title.toLowerCase().includes(q)
      );
      if (!sop) {
        return {
          content: [{ type: "text", text: `No SOP matched "${search}".` }],
          isError: true
        };
      }
      const latest = sop.versions[sop.versions.length - 1];
      return {
        content: [
          {
            type: "text",
            text: `# ${sop.title}
Category: ${sop.category}
Version ${latest?.version} \xB7 updated ${sop.updatedAt}

${latest?.content ?? ""}`
          }
        ]
      };
    }
    const rows = filtered.map((s) => ({
      id: s.id,
      title: s.title,
      category: s.category,
      updatedAt: s.updatedAt,
      versions: s.versions.length
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { count: rows.length, sops: rows }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "xembwxgilrsjeybuwxwt";
var mcp_default = defineMcp({
  name: "home-care-hub",
  title: "Home Care Hub",
  version: "0.1.0",
  instructions: "Read-only operations tools for the Home Care Hub agency dashboard. Use query_clients, query_employees, query_shifts and query_invoices to answer questions about people, schedules and billing, and get_sops for standard operating procedures.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [query_clients_default, query_employees_default, query_shifts_default, query_invoices_default, get_sop_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
