// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/query-clients.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^4.4.3";

// src/lib/mockData.ts
var uid = /* @__PURE__ */ (() => {
  let i = 1;
  return () => `id_${i++}`;
})();
var today = /* @__PURE__ */ new Date();
var dayStart = new Date(today.getFullYear(), today.getMonth(), today.getDate());
var weekStart = new Date(dayStart);
weekStart.setDate(dayStart.getDate() - dayStart.getDay());
function iso(d) {
  return d.toISOString();
}
function addDays(d, n) {
  const x = new Date(d);
  x.setDate(x.getDate() + n);
  return x;
}
function addHours(d, n) {
  const x = new Date(d);
  x.setHours(x.getHours() + n);
  return x;
}
function setTime(d, h, m = 0) {
  const x = new Date(d);
  x.setHours(h, m, 0, 0);
  return x;
}
var employees = [
  ["Chanel P", "Caregiver"],
  ["Bedjine Cupidon", "Caregiver"],
  ["Heather Gonzales", "Caregiver"],
  ["Tanya Robinson", "Caregiver"],
  ["Vanessa", "Caregiver"],
  ["Thylia", "Caregiver"],
  ["Emone", "Caregiver"],
  ["Kelsey Westley", "RN"],
  ["John Segura", "Coordinator"]
].map(([name, role], i) => ({
  id: uid(),
  name,
  role,
  status: i === 4 ? "on-leave" : "active",
  hoursThisWeek: 18 + i * 7 % 24,
  email: name.toLowerCase().replace(/[^a-z]+/g, ".") + "@joyhealthcare.example",
  phone: `555-01${(20 + i).toString().padStart(2, "0")}`,
  hireDate: iso(addDays(today, -300 - i * 40)),
  credentials: [
    { name: "CPR", expires: iso(addDays(today, 30 + i * 13 % 200 - 50)) },
    { name: "First Aid", expires: iso(addDays(today, 90 + i * 17 % 250)) }
  ],
  assignedClientIds: []
}));
var clientNames = [
  "Lian Huang",
  "Edward Pham",
  "Dolores Vance",
  "Susan Miller",
  "Ruth Alvarez",
  "Evelyn Carter",
  "Theo Nakamura",
  "Augustin Vandermeer"
];
var clients = clientNames.map((name, i) => ({
  id: uid(),
  name,
  status: i % 11 === 0 ? "on-hold" : i % 17 === 0 ? "discharged" : "active",
  primaryCaregiverId: employees[i % employees.length].id,
  carePlan: ["Standard Care", "Memory Care", "Post-Op Recovery", "Companion Care", "Skilled Nursing"][i % 5],
  hoursPerWeek: 8 + i * 5 % 40,
  address: `${100 + i * 7} ${["Maple", "Oak", "Cedar", "Pine", "Birch"][i % 5]} St, Houston`,
  phone: `555-02${(10 + i).toString().padStart(2, "0")}`,
  email: name.toLowerCase().replace(/[^a-z]+/g, ".") + "@example.com",
  dob: iso(addDays(today, -365 * (65 + i % 25))),
  notes: ""
}));
clients.forEach((c) => {
  if (c.primaryCaregiverId) {
    const e = employees.find((x) => x.id === c.primaryCaregiverId);
    if (e) e.assignedClientIds.push(c.id);
  }
});
var shifts = [];
for (let day = 0; day < 7; day++) {
  for (let s = 0; s < 12; s++) {
    const date = addDays(weekStart, day);
    const startHour = [7, 9, 11, 13, 15, 17][s % 6];
    const start = setTime(date, startHour);
    const end = addHours(start, 2 + s % 3);
    const cg = employees[(day * 3 + s) % employees.length];
    const cl = clients[(day * 5 + s * 2) % clients.length];
    let status = "scheduled";
    if (date < dayStart) status = s % 9 === 0 ? "missed" : "completed";
    else if (date.getTime() === dayStart.getTime() && start < today) {
      status = today < end ? "clocked-in" : s % 11 === 0 ? "missed" : "completed";
    }
    shifts.push({
      id: uid(),
      caregiverId: cg.id,
      clientId: cl.id,
      start: iso(start),
      end: iso(end),
      status
    });
  }
}
var invoices = clients.slice(0, 12).map((c, i) => ({
  id: uid(),
  number: `INV-${2025}-${(100 + i).toString().padStart(4, "0")}`,
  clientId: c.id,
  amount: 800 + i * 137 % 4e3,
  status: ["paid", "sent", "draft", "overdue", "paid", "sent"][i % 6],
  periodStart: iso(addDays(today, -30)),
  periodEnd: iso(addDays(today, -1)),
  issuedAt: iso(addDays(today, -(i * 3 % 25)))
}));
var documents = [
  ["Employee Handbook 2025.pdf", "Policies", "pdf"],
  ["HIPAA Compliance Guide.pdf", "Compliance", "pdf"],
  ["Onboarding Checklist.docx", "Onboarding", "docx"],
  ["W-2 Template.pdf", "HR", "pdf"],
  ["Care Plan Template.docx", "Templates", "docx"],
  ["Q1 Financials.xlsx", "Finance", "xlsx"],
  ["Brand Guidelines.pdf", "Marketing", "pdf"],
  ["Office Photo.jpg", "Marketing", "image"],
  ["Insurance Certificate.pdf", "Compliance", "pdf"],
  ["Caregiver Performance Reviews.xlsx", "HR", "xlsx"],
  ["Emergency Contact List.docx", "HR", "docx"],
  ["State License.pdf", "Compliance", "pdf"]
].map(([name, folder, type], i) => ({
  id: uid(),
  name,
  folder,
  type,
  ownerId: employees[i % employees.length].id,
  uploadedAt: iso(addDays(today, -(i * 4 % 90))),
  size: 5e4 + i * 18e3,
  permission: ["everyone", "admins", "managers", "everyone"][i % 4]
}));
var goalSeed = [
  ["Reach 100 active clients", 78],
  ["Reduce missed shifts by 50%", 62],
  ["Onboard 10 new caregivers in Q2", 40],
  ["Achieve 95% billing on time", 88],
  ["Launch caregiver mobile app", 25],
  ["Complete annual HIPAA training", 95],
  ["Reduce overtime by 20%", 55],
  ["Improve client NPS to 70", 45]
];
var goals = goalSeed.map(([title, progress], i) => {
  const status = progress >= 90 ? "done" : progress >= 60 ? "on-track" : progress >= 40 ? "at-risk" : "off-track";
  return {
    id: uid(),
    title,
    description: "Strategic goal aligned with quarterly objectives.",
    ownerId: employees[i % employees.length].id,
    dueDate: iso(addDays(today, 30 + i * 15)),
    status,
    progress,
    milestones: [
      { id: uid(), title: "Define plan", done: true, due: iso(addDays(today, -20)) },
      { id: uid(), title: "Kick off with team", done: progress > 30, due: iso(addDays(today, -5)) },
      { id: uid(), title: "Mid-point review", done: progress > 60, due: iso(addDays(today, 15)) },
      { id: uid(), title: "Final delivery", done: progress >= 100, due: iso(addDays(today, 45)) }
    ]
  };
});
var sopTitles = [
  ["New Caregiver Orientation", "Onboarding"],
  ["Client Intake Process", "Onboarding"],
  ["Hand Hygiene Protocol", "Care Procedures"],
  ["Medication Reminders", "Care Procedures"],
  ["Fall Prevention", "Care Procedures"],
  ["Wound Care Basics", "Care Procedures"],
  ["HIPAA Privacy Rules", "Compliance"],
  ["Background Check Procedure", "Compliance"],
  ["Incident Reporting", "Compliance"],
  ["Fire Emergency Response", "Emergency"],
  ["Medical Emergency Protocol", "Emergency"],
  ["Severe Weather Plan", "Emergency"],
  ["Invoice Generation", "Billing"],
  ["Insurance Claim Submission", "Billing"],
  ["Time Off Request Process", "HR"],
  ["Performance Review Cycle", "HR"],
  ["Disciplinary Process", "HR"],
  ["End of Shift Documentation", "Care Procedures"],
  ["Client Discharge Process", "Onboarding"],
  ["Caregiver Termination", "HR"]
];
var sops = sopTitles.map(([title, category], i) => ({
  id: uid(),
  title,
  category,
  ownerId: employees[i % employees.length].id,
  updatedAt: iso(addDays(today, -(i * 6 % 120))),
  versions: [
    {
      version: 1,
      updatedAt: iso(addDays(today, -(i * 6 % 120) - 30)),
      updatedBy: employees[i % employees.length].id,
      content: `<h2>Purpose</h2><p>This SOP outlines the standard procedure for ${title.toLowerCase()}.</p><h2>Scope</h2><p>Applies to all staff in the ${category} domain.</p><h2>Procedure</h2><ol><li>Identify the situation requiring action.</li><li>Follow company-approved checklist.</li><li>Document the action in the client record.</li><li>Notify supervisor if escalation is required.</li></ol><h2>References</h2><p>See related policies in the Documents section.</p>`
    },
    {
      version: 2,
      updatedAt: iso(addDays(today, -(i * 6 % 120))),
      updatedBy: employees[(i + 1) % employees.length].id,
      content: `<h2>Purpose</h2><p>This SOP outlines the standard procedure for ${title.toLowerCase()}, updated for 2025 compliance.</p><h2>Scope</h2><p>Applies to all staff in the ${category} domain.</p><h2>Procedure</h2><ol><li>Identify the situation requiring action.</li><li>Follow the updated 2025 company-approved checklist.</li><li>Document the action in the client record within 24 hours.</li><li>Notify supervisor and on-call manager if escalation is required.</li></ol><h2>References</h2><p>See related policies in the Documents section and the Compliance handbook.</p>`
    }
  ]
}));
var activity = [
  { id: uid(), kind: "client", message: "New client Eleanor Whitfield admitted", at: iso(addHours(today, -1)) },
  { id: uid(), kind: "shift", message: "Jordan Lee completed shift with Harold Stein", at: iso(addHours(today, -2)) },
  { id: uid(), kind: "document", message: "Kelsey Westley uploaded Care Plan Template.docx", at: iso(addHours(today, -4)) },
  { id: uid(), kind: "goal", message: "Goal 'Reduce overtime by 20%' updated to 55%", at: iso(addHours(today, -7)) },
  { id: uid(), kind: "sop", message: "SOP 'Fall Prevention' was revised", at: iso(addHours(today, -10)) },
  { id: uid(), kind: "shift", message: "Sofia Ramirez clocked in for Margaret O'Hara", at: iso(addHours(today, -12)) },
  { id: uid(), kind: "client", message: "Doris Kapoor moved to On Hold", at: iso(addHours(today, -20)) }
];
var alerts = [
  { id: uid(), severity: "danger", title: "Missed clock-in", detail: "Liam O'Connor missed 9:00 AM shift with Walter Nakamura", createdAt: iso(addHours(today, -1)) },
  { id: uid(), severity: "warning", title: "Credential expiring", detail: "Aisha Bello's CPR cert expires in 12 days", createdAt: iso(addHours(today, -3)) },
  { id: uid(), severity: "warning", title: "Unassigned shift", detail: "Tomorrow 2:00 PM \u2014 Beatrice Coleman has no caregiver", createdAt: iso(addHours(today, -5)) },
  { id: uid(), severity: "info", title: "Care plan renewal", detail: "Frank Delgado's care plan expires in 7 days", createdAt: iso(addHours(today, -8)) },
  { id: uid(), severity: "warning", title: "Overtime risk", detail: "Tanya Robinson will exceed 40h this week", createdAt: iso(addHours(today, -12)) }
];
var mockDB = {
  clients,
  employees,
  shifts,
  invoices,
  documents,
  goals,
  sops,
  activity,
  alerts
};

// src/lib/mcp/auth.ts
function requireAuth(ctx) {
  if (ctx?.isAuthenticated?.()) return null;
  return {
    content: [
      {
        type: "text",
        text: "Not authenticated. Sign in to Home Care Hub to use this tool."
      }
    ],
    isError: true
  };
}

// src/lib/mcp/tools/query-clients.ts
var query_clients_default = defineTool({
  name: "query_clients",
  title: "Query clients",
  description: "Search home-care clients by name or status. Returns matching clients with care plan, weekly hours, and primary caregiver.",
  inputSchema: {
    search: z.string().optional().describe("Partial, case-insensitive name match"),
    status: z.enum(["active", "on-hold", "discharged"]).optional(),
    limit: z.number().int().min(1).max(50).default(20)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ search, status, limit }, ctx) => {
    const denied = requireAuth(ctx);
    if (denied) return denied;
    const rows = mockDB.clients.filter((c) => status ? c.status === status : true).filter((c) => search ? c.name.toLowerCase().includes(search.toLowerCase()) : true).slice(0, limit).map((c) => ({
      id: c.id,
      name: c.name,
      status: c.status,
      carePlan: c.carePlan,
      hoursPerWeek: c.hoursPerWeek,
      primaryCaregiver: mockDB.employees.find((e) => e.id === c.primaryCaregiverId)?.name ?? null
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { count: rows.length, clients: rows }
    };
  }
});

// src/lib/mcp/tools/query-employees.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^4.4.3";
var query_employees_default = defineTool2({
  name: "query_employees",
  title: "Query caregivers",
  description: "Search caregivers and staff by name, role, or status. Includes hours this week and credential expiry dates.",
  inputSchema: {
    search: z2.string().optional(),
    role: z2.enum(["Caregiver", "RN", "LPN", "Coordinator"]).optional(),
    status: z2.enum(["active", "on-leave", "inactive"]).optional(),
    limit: z2.number().int().min(1).max(50).default(20)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ search, role, status, limit }, ctx) => {
    const denied = requireAuth(ctx);
    if (denied) return denied;
    const rows = mockDB.employees.filter((e) => role ? e.role === role : true).filter((e) => status ? e.status === status : true).filter((e) => search ? e.name.toLowerCase().includes(search.toLowerCase()) : true).slice(0, limit).map((e) => ({
      id: e.id,
      name: e.name,
      role: e.role,
      status: e.status,
      hoursThisWeek: e.hoursThisWeek,
      credentials: e.credentials,
      assignedClients: e.assignedClientIds.length
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { count: rows.length, employees: rows }
    };
  }
});

// src/lib/mcp/tools/query-shifts.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^4.4.3";
function windowFor(when) {
  const now = /* @__PURE__ */ new Date();
  const start = new Date(now);
  start.setHours(0, 0, 0, 0);
  const end = new Date(start);
  switch (when) {
    case "tomorrow":
      start.setDate(start.getDate() + 1);
      end.setDate(start.getDate() + 1);
      break;
    case "this-week":
      end.setDate(start.getDate() + 7);
      break;
    case "next-week":
      start.setDate(start.getDate() + 7);
      end.setDate(start.getDate() + 7);
      break;
    case "past-week":
      start.setDate(start.getDate() - 7);
      break;
    default:
      end.setDate(start.getDate() + 1);
  }
  return [start, end];
}
var query_shifts_default = defineTool3({
  name: "query_shifts",
  title: "Query shifts",
  description: "Look up scheduled shifts in a date window, optionally filtered by caregiver, client, or shift status.",
  inputSchema: {
    when: z3.enum(["today", "tomorrow", "this-week", "next-week", "past-week"]).default("today"),
    caregiverName: z3.string().optional(),
    clientName: z3.string().optional(),
    status: z3.enum(["scheduled", "clocked-in", "completed", "missed", "cancelled"]).optional(),
    limit: z3.number().int().min(1).max(100).default(50)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ when, caregiverName, clientName, status, limit }, ctx) => {
    const denied = requireAuth(ctx);
    if (denied) return denied;
    const [from, to] = windowFor(when);
    const rows = mockDB.shifts.filter((s) => {
      const start = new Date(s.start);
      return start >= from && start < to;
    }).filter((s) => status ? s.status === status : true).map((s) => ({
      id: s.id,
      start: s.start,
      end: s.end,
      status: s.status,
      caregiver: mockDB.employees.find((e) => e.id === s.caregiverId)?.name ?? "Unknown",
      client: mockDB.clients.find((c) => c.id === s.clientId)?.name ?? "Unknown",
      notes: s.notes ?? null
    })).filter(
      (s) => caregiverName ? s.caregiver.toLowerCase().includes(caregiverName.toLowerCase()) : true
    ).filter(
      (s) => clientName ? s.client.toLowerCase().includes(clientName.toLowerCase()) : true
    ).sort((a, b) => a.start.localeCompare(b.start)).slice(0, limit);
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { count: rows.length, window: when, shifts: rows }
    };
  }
});

// src/lib/mcp/tools/query-invoices.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z4 } from "npm:zod@^4.4.3";
var query_invoices_default = defineTool4({
  name: "query_invoices",
  title: "Query invoices",
  description: "List billing invoices, optionally filtered by status or client name, with totals for the matching set.",
  inputSchema: {
    status: z4.enum(["draft", "sent", "paid", "overdue"]).optional(),
    clientName: z4.string().optional(),
    limit: z4.number().int().min(1).max(100).default(25)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ status, clientName, limit }, ctx) => {
    const denied = requireAuth(ctx);
    if (denied) return denied;
    const rows = mockDB.invoices.filter((i) => status ? i.status === status : true).map((i) => ({
      id: i.id,
      number: i.number,
      client: mockDB.clients.find((c) => c.id === i.clientId)?.name ?? "Unknown",
      amount: i.amount,
      status: i.status,
      periodStart: i.periodStart,
      periodEnd: i.periodEnd,
      issuedAt: i.issuedAt
    })).filter(
      (i) => clientName ? i.client.toLowerCase().includes(clientName.toLowerCase()) : true
    ).slice(0, limit);
    const total = rows.reduce((sum, r) => sum + r.amount, 0);
    return {
      content: [
        { type: "text", text: JSON.stringify({ total, invoices: rows }, null, 2) }
      ],
      structuredContent: { count: rows.length, total, invoices: rows }
    };
  }
});

// src/lib/mcp/tools/get-sop.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z5 } from "npm:zod@^4.4.3";
var get_sop_default = defineTool5({
  name: "get_sops",
  title: "Get SOPs",
  description: "List standard operating procedures, or fetch the latest content of one SOP by id or title match.",
  inputSchema: {
    search: z5.string().optional().describe("Title or id to fetch full content for"),
    category: z5.string().optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ search, category }, ctx) => {
    const denied = requireAuth(ctx);
    if (denied) return denied;
    const filtered = mockDB.sops.filter(
      (s) => category ? s.category.toLowerCase() === category.toLowerCase() : true
    );
    if (search) {
      const q = search.toLowerCase();
      const sop = filtered.find(
        (s) => s.id.toLowerCase() === q || s.title.toLowerCase().includes(q)
      );
      if (!sop) {
        return {
          content: [{ type: "text", text: `No SOP matched "${search}".` }],
          isError: true
        };
      }
      const latest = sop.versions[sop.versions.length - 1];
      return {
        content: [
          {
            type: "text",
            text: `# ${sop.title}
Category: ${sop.category}
Version ${latest?.version} \xB7 updated ${sop.updatedAt}

${latest?.content ?? ""}`
          }
        ]
      };
    }
    const rows = filtered.map((s) => ({
      id: s.id,
      title: s.title,
      category: s.category,
      updatedAt: s.updatedAt,
      versions: s.versions.length
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { count: rows.length, sops: rows }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "xembwxgilrsjeybuwxwt";
var mcp_default = defineMcp({
  name: "home-care-hub",
  title: "Home Care Hub",
  version: "0.1.0",
  instructions: "Read-only operations tools for the Home Care Hub agency dashboard. Use query_clients, query_employees, query_shifts and query_invoices to answer questions about people, schedules and billing, and get_sops for standard operating procedures.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [query_clients_default, query_employees_default, query_shifts_default, query_invoices_default, get_sop_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
